version: '2'
services:
  backend:
    build: .
    container_name: "myapp"
    image: urlshortener/backend
    ports:
      - 9001:8080
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=~/tmp
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ~/tmp:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet